// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheSpaceport;

namespace TheSpaceport.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200322143647_addtest")]
    partial class addtest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TheSpaceport.DataBasePerson", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StartshipShipID")
                        .HasColumnType("int");

                    b.HasKey("PersonID");

                    b.HasIndex("StartshipShipID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("TheSpaceport.DataBaseStartship", b =>
                {
                    b.Property<int>("ShipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("int");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<int>("PricePerDay")
                        .HasColumnType("int");

                    b.Property<string>("ShipName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShipID");

                    b.ToTable("Spaceships");
                });

            modelBuilder.Entity("TheSpaceport.DataBasePerson", b =>
                {
                    b.HasOne("TheSpaceport.DataBaseStartship", "Startship")
                        .WithMany("Person")
                        .HasForeignKey("StartshipShipID");
                });
#pragma warning restore 612, 618
        }
    }
}
